/** Flow slugs — source format for in-memory catalog (labels in i18n). */
export const FLOW_SLUGS = [
  'insect',
  'air',
  'water',
  'shelter',
  'protection',
  'community',
  'grit',
  'dust',
  'disease-control',
  'egg',
  'meat',
  'manure',
  'feather',
  'scraping',
  'co2',
  'heat',
  'deworming',
  'soil',
  'sunlight',
  'space',
  'micro-climate',
  'oxygen',
  'wood',
  'shade',
  'windbreak',
  'habitat',
  'acorn',
  'moisture',
  'leaf',
] as const
